# -*- coding: UTF-8 -*-
"""
	Copyright to be determined - copied from OSHIP

	Reference: datatypes_im.pdf Chapter 4 - Basic Package
"""


class DataValue(object):
    """
    Abstract class.
    Serves as a common ancestor of all data value types in openEHR models.
    """


class DvBoolean(DataValue):
    """
    Items which are truly boolean data, such as true/false answers.
    For such data, it is important to devise the meanings (usually questions in subjec-
    tive data) carefully, so that the only allowed results are in fact true or false.
    The DV_BOOLEAN class should not be used as a replacement for naively modelled
    enumerated types such as male/female etc. Such values should be coded, and in
    any case the enumeration often has more than two values.
    """

    def __init__(self, value):
        self.value = value


class DvIdentifier(DataValue):
    """
    Type for representing identifiers of real-world entities. Typical identifiers include
    drivers licence number, social security number, vertans affairs number, prescrip-
    tion id, order id, and so on.
    DV_IDENTIFIER is used to represent any identifier of a real thing, issued by
    some authority or agency.
    DV_IDENTIFIER is not used to express identifiers generated by the infrastruc-
    ture to refer to information items; the types OBJECT_ID and OBJECT_REF and
    subtypes are defined for this purpose.
    """

    def __init__(self, issuer, assigner, id, type):
            self.issuer = issuer
            self.assigner = assigner
            self.id = id
            self.type = type


class DvState(DataValue):
    """
    For representing state values which obey a defined state machine, such as a vari-
    able representing the states of an instruction or care process.
    """

    def __init__(self,value,isTerminal):
        self.value=value
        self.isTerminal=isTerminal

